Fix issue attribute error in queue
When multinode jobs are queued, the master scheduler
fails to start single node jobs for idle devices because
of an exception in queue handling:
AttributeError: 'QuerySet' object has no attribute 'append'

Fix public devices check to ensure that devices remains a
list, not a QuerySet as we need to use append().

Change-Id: I52110ab3eebf7ee4af98fab7c2a2a88bd7e01b77