tests: fix test_download_decompression_map test
When running on the local, it always returns the below error as
`/dev/null` is not a directory, but `decompress_file()` needs to change
into it.

```
NotADirectoryError: [Errno 20] Not a directory: '/dev/null'
```

This change uses a temporary directory for the test.

Signed-off-by: Chase Qi <chase.qi@linaro.org>