Fix missing check for u-boot commands parameters
When booting with U-Boot, the 'commands' parameters is required.  If
not provided in the job, an exception is raised when the code tries to
access it:

  KeyError: 'commands'

Check that the 'commands' parameter is present along with other
required parameters and raise a clear ConfigurationError if not.

Change-Id: Iaea1545b5565a19f17b8edb83d839768b7cefa11
Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>