lava_scheduler_app: skip yaml syntax validation when deleting worker configs
Trying to validate an empty configure like `None` is nonsense and
throws the below exception.

```
TypeError: a string or stream input is required
```

Signed-off-by: Chase Qi <chase.qi@linaro.org>