tests: Fix raise NotImplemented instead of raise NotImplementedError
NotImplemented is not actually an exception. The actual exception
is the NotImplementedError.

Trying to raise exception from NotImplemented will raise

```
TypeError: exceptions must derive from BaseException
```