Fixes missing key that came in on 6b80426e. AttributeError: 'Scp' object has no attribute 'key'.
The commit "Remove unused key parameter from Scp action" introduced a
regression causing an `AttributeError: 'Scp' object has no attribute
'key'.

This was because the `Scp` child class no longer set `self.key`, but the
`ConnectSsh` parent class's `run` method still expected it to exist inside
a conditional check.

Fixes: 6b80426e68f8064232542bbfda79a329fc0a2bee

Signed-off-by: Ben Copeland <ben.copeland@linaro.org>
Suggested-by: Chase Qi <chase.qi@linaro.org>