Fix 500 when device-type template does not exist
The crash was found on staging for juno-r2 device-type:
  [...]
  File "/usr/lib/python2.7/dist-packages/lava_scheduler_app/views.py", line 818, in device_type_detail
    'health_freq': health_freq_str})
  [...]
  File "/usr/lib/python2.7/dist-packages/django/template/defaultfilters.py", line 582, in join
    value = map(force_text, value)
TypeError: argument 2 to map() must support iteration

Change-Id: If0e16351db406c274acd087000fe407b968b202e