Fix ValueError when closing the connection twice
```python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lava_dispatcher/shell.py", line 195, in _expect_exc_wrapper
    yield None
  File "/usr/lib/python3/dist-packages/lava_dispatcher/shell.py", line 443, in listen_feedback
    self.raw_connection.expect(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        [".+", pexpect.EOF, pexpect.TIMEOUT], timeout=timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 354, in expect
    return self.expect_list(compiled_pattern_list,
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
            timeout, searchwindowsize, async_)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 383, in expect_list
    return exp.expect_loop(timeout)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 169, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 443, in read_nonblocking
    raise ValueError('I/O operation on closed file.')
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lava_dispatcher/power.py", line 341, in run
    connection = super().run(connection, max_end_time)
  File "/usr/lib/python3/dist-packages/lava_dispatcher/action.py", line 883, in run
    return self.pipeline.run_actions(connection, max_end_time)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lava_dispatcher/action.py", line 243, in run_actions
    new_connection = action.run(connection, action_max_end_time)
  File "/usr/lib/python3/dist-packages/lava_dispatcher/power.py", line 288, in run
    bytes_read = feedback[1].listen_feedback(
        timeout=timeout, namespace=feedback[0]
    )
  File "/usr/lib/python3/dist-packages/lava_dispatcher/shell.py", line 442, in listen_feedback
    with self._expect_exc_wrapper():
         ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/lib/python3/dist-packages/lava_dispatcher/shell.py", line 202, in _expect_exc_wrapper
    raise TestError(exc)
lava_common.exceptions.TestError: I/O operation on closed file.
```

Signed-off-by: Rémi Duraffort <remi.duraffort@linaro.org>